steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'deploy/gcp/Dockerfile'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cleaner-code/cleaner-code-api:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cleaner-code/cleaner-code-api:latest'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cleaner-code-api'
      - '--image'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cleaner-code/cleaner-code-api:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-northeast3'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '60'
      - '--concurrency'
      - '20'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,API_VALIDATE_URL=https://cleanercode.pages.dev/api/validate-key,USAGE_URL=https://cleanercode.pages.dev/api/usage'
images:
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cleaner-code/cleaner-code-api:latest'
timeout: '1200s'
